### ISSUE TITLE
Check Null Values

### ISSUE THREAD

**Issue by zuil7** [dgrzeszczak/KeyedCodable#2]
Hi,

Great library you have here. I am currently using your library. i am facing issue on how to check null values. 

Example:
{"data":null,"message":"User not found.","status_code":401}

Snippet:
```
struct LoginResponse: Decodable,Keyedable {
    var user: User?
    var message: String!
    var status_code: NSInteger!
    
    mutating func map(map: KeyMap) throws {
        try user <<- map["data.user"]
        try message <<- map["message"]
        try status_code <<- map["status_code"]

    }
    init(from decoder: Decoder) throws {
        try KeyedDecoder(with: decoder).decode(to: &self)
    }
}

```
app keeps crashing because of the null value.

Hope you can help me on this.

Thanks,

**Comment by dgrzeszczak** [comment]
hey, it looks like on swift5 update methods with optional parameters work differently than on swift 4 (what version do you use?). I will look what we are able to do but it looks we have to change the operators.

For now you can try to use optional try for that property ```try? message <<- map["data.user"]```

**Comment by dgrzeszczak** [comment]
@zuil7 new 1.2.0 version is released. Unfortunately latest swift changes blocks the possibility to use the same operators for optionals and implicity unwrapped optionals. Please use IfPresend equivalent for optional properties so it would look like ```try user <<? map["data.user"]```. Please let me know if that is working for you. Thanks
