### ISSUE TITLE
Bazel build

### ISSUE THREAD

**Issue by yuriy-yarosh** [dgrzeszczak/KeyedCodable#4]
Could you, please, add an explicit `import Foundation` at Helpers.swift ? 
So, bazel would be able to link the respective framework automatically with `swift_library` rule:

```
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "keyedcodable",
    module_name = "KeyedCodable",
    srcs = glob(["KeyedCodable/Sources/**/*.swift"]),
)
```

Thanks.

**Comment by dgrzeszczak** [comment]
I've added the imports, hope it helps ;) (version 3.0.1)

**Comment by yuriy-yarosh** [comment]
Thanks, man.

Yes, it does indeed.
